### PR TITLE
Register actx.np.stack

### PR DESCRIPTION
**Pull request by kaushikcfd**

### CODE REVIEW

**Comment by inducer** [comment]
I just released pyopencl 2021.1.6 to include `cla.stack`. It should make its way to c-f before too long. After that, pylint should start passing.

**Comment by kaushikcfd** [comment]
@inducer: Thank you!

**Comment by inducer** [comment]
https://github.com/conda-forge/pyopencl-feedstock/pull/62

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
