### PR TITLE
_reshape_and_preserve_tags: support untaggable arrays

### PR DESCRIPTION
**Pull request by matthiasdiener**
(e.g. np.ndarray)

cc https://github.com/inducer/arraycontext/pull/235

### CODE REVIEW

**Comment by inducer** [comment]
I'm not sure why that'd be necessary. For arrays that don't do tagging, wouldn't `actx.tag` be a no-op?

**Comment by matthiasdiener** [comment]
> I'm not sure why that'd be necessary. For arrays that don't do tagging, wouldn't `actx.tag` be a no-op?

`actx.tag` is a no-op in https://github.com/inducer/arraycontext/pull/235, but `ary.tags` won't work (since `ary` is an ndarray in that case).

**Comment by inducer** [comment]
> `actx.tag` is a no-op in [inducer/arraycontext#235](https://github.com/inducer/arraycontext/pull/235), but `ary.tags` won't work (since `ary` is an ndarray in that case).

That makes sense. But in that case, only the access `ary.tags` should be in the `try` block.

**Comment by matthiasdiener** [comment]
> That makes sense. But in that case, only the access `ary.tags` should be in the `try` block.

What do you think of 50f3134?

**Comment by inducer** [comment]
LGTM, thanks!

**Pull request merged**
