### PR TITLE
`test_element_orientation_via_single_elements` (from @lukeolson)

### PR DESCRIPTION
**Pull request by inducer**
Curiously, there *are* some disagreements here.

cc @lukeolson

### CODE REVIEW

**Comment by lukeolson** [comment]
Yep, I see that too.  It fails on this:
```python
import numpy as np
vert = np.array([[1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 0],
                 [0, 0, 1]])
G = np.append(vert, np.ones((4, 1)), axis=1)

print(G)
print(np.linalg.det(G))
```
which gives
```
[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 1.]]
-1.0
```

So it appears it should be negative.

**Comment by inducer** [comment]
404f709c08c0df904340762faaf6d18239ce5d7b has the data directly copied from https://github.com/lukeolson/mesh_orientation/blob/460bb2b634e2abb6aa32c3d02e2c732969bf08bf/check.py, and it seems everybody's in agreement now.

@lukeolson, how do you feel about this?

**Comment by lukeolson** [comment]
The test looks good.

**Comment by inducer** [comment]
Thanks for taking a look!

**Pull request merged**
