### PR TITLE
Periodic boundaries in meshmode

### PR DESCRIPTION
**Pull request by MTCam**
Not sure this is heading in the right direction.  I think it has led me to a layer too deep with needing to modify InterpolationBatch.   Any guidance would be deeply appreciated @inducer :)

### CODE REVIEW

**Comment by MTCam** [comment]
Yikes.  I deleted the meshmode fork from illinois-ceesd and lost the periodic bc stuff.  This broken PR is my only record of it :(

**Comment by inducer** [comment]
Shouldn't be a big deal. Your last commit (a3fcf8e0847b013f80adecf54bc608f23441aae8) is accessible via this repo, so you can just pull from that.

**Comment by MTCam** [comment]
Yay :) Thanks so much.

**Comment by MTCam** [comment]
> Shouldn't be a big deal. Your last commit ([a3fcf8e](https://github.com/inducer/meshmode/commit/a3fcf8e0847b013f80adecf54bc608f23441aae8)) is accessible via this repo, so you can just pull from that. (by directly referencing the commit SHA, not any branch name)

I'm not sure:
```
(dgfem3) Michaels-MBP:meshmode mtcampbe$ git checkout a3fcf8e
error: pathspec 'a3fcf8e' did not match any file(s) known to git
(dgfem3) Michaels-MBP:meshmode mtcampbe$ git remote -v
origin	git@github.com:inducer/meshmode (fetch)
origin	git@github.com:inducer/meshmode (push)
```

**Pull request closed without merging**
