### PR TITLE
Allow distributed partition boundaries to be not just rank boundaries

### PR DESCRIPTION
**Pull request by inducer**
To do before merging:

- [x] Decide on #308
- [ ] ~~Decide on #309~~ (we'll merge this separately)

cc @majosm

### CODE REVIEW

**Comment by inducer** [comment]
I'll wait with merging this until we figure out what should happen to #308 and #309.

**Comment by inducer** [comment]
I think I've managed a clean rebase, there wasn't much to do. The diff between 4f7bc427f7370a2f2ec6b9742e8eec405d65fce6 (prior state) and 28d2f34c6ba2991454174139785a6b5516236952 (current state) is empty for me.

**Comment by inducer** [comment]
The flake8 failure seems to be a recent release of flake8-bugbear: https://pypi.org/project/flake8-bugbear/22.7.1/

**Comment by majosm** [comment]
> The flake8 failure seems to be due to a recent release of flake8-bugbear: https://pypi.org/project/flake8-bugbear/22.7.1/

Yeah, getting some in grudge too:

```
grudge/trace_pair.py:434:28: B023 Function definition does not bind loop variable 'other_to_self'.
[80](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:81)
test/test_grudge.py:705:23: B023 Function definition does not bind loop variable 'v'.
[81](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:82)
test/test_grudge.py:705:32: B023 Function definition does not bind loop variable 'norm_v'.
[82](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:83)
test/test_grudge.py:705:43: B023 Function definition does not bind loop variable 'norm_v'.
[83](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:84)
test/test_grudge.py:717:47: B023 Function definition does not bind loop variable 'dcoll'.
[84](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:85)
test/test_grudge.py:726:20: B023 Function definition does not bind loop variable 'adv_operator'.
[85](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:86)
test/test_grudge.py:831:20: B023 Function definition does not bind loop variable 'maxwell_operator'.
[86](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:87)
test/test_grudge.py:917:24: B023 Function definition does not bind loop variable 'dcoll'.
[87](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:88)
test/test_euler_model.py:96:20: B023 Function definition does not bind loop variable 'euler_operator'.
[88](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:89)
test/test_op.py:70:22: B023 Function definition does not bind loop variable 'dcoll'.
[89](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:90)
test/test_op.py:72:55: B023 Function definition does not bind loop variable 'i'.
[90](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:91)
test/test_op.py:77:38: B023 Function definition does not bind loop variable 'dcoll'.
[91](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:92)
test/test_op.py:79:32: B023 Function definition does not bind loop variable 'i'.
[92](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:93)
test/test_op.py:80:28: B023 Function definition does not bind loop variable 'i'.
[93](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:94)
test/test_op.py:80:40: B023 Function definition does not bind loop variable 'i'.
[94](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:95)
test/test_op.py:81:24: B023 Function definition does not bind loop variable 'i'.
[95](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:96)
test/test_op.py:81:36: B023 Function definition does not bind loop variable 'i'.
[96](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:97)
test/test_op.py:81:67: B023 Function definition does not bind loop variable 'i'.
[97](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:98)
test/test_op.py:82:32: B023 Function definition does not bind loop variable 'i'.
[98](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:99)
test/test_op.py:83:28: B023 Function definition does not bind loop variable 'i'.
[99](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:100)
test/test_op.py:83:40: B023 Function definition does not bind loop variable 'i'.
[100](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:101)
test/test_op.py:84:24: B023 Function definition does not bind loop variable 'i'.
[101](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:102)
test/test_op.py:84:36: B023 Function definition does not bind loop variable 'i'.
[102](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:103)
test/test_op.py:100:32: B023 Function definition does not bind loop variable 'dcoll'.
[103](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:104)
test/test_op.py:109:31: B023 Function definition does not bind loop variable 'dcoll'.
[104](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:105)
test/test_op.py:109:42: B023 Function definition does not bind loop variable 'dd_allfaces'.
[105](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:106)
test/test_op.py:190:38: B023 Function definition does not bind loop variable 'dcoll'.
[106](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:107)
test/test_op.py:190:59: B023 Function definition does not bind loop variable 'i'.
[107](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:108)
test/test_op.py:192:55: B023 Function definition does not bind loop variable 'i'.
[108](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:109)
test/test_op.py:197:22: B023 Function definition does not bind loop variable 'dcoll'.
[109](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:110)
test/test_op.py:199:25: B023 Function definition does not bind loop variable 'dcoll'.
[110](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:111)
test/test_op.py:199:46: B023 Function definition does not bind loop variable 'i'.
[111](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:112)
test/test_op.py:200:32: B023 Function definition does not bind loop variable 'i'.
[112](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:113)
test/test_op.py:202:59: B023 Function definition does not bind loop variable 'i'.
[113](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:114)
test/test_op.py:203:32: B023 Function definition does not bind loop variable 'i'.
[114](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:115)
test/test_op.py:207:21: B023 Function definition does not bind loop variable 'dcoll'.
[115](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:116)
test/test_op.py:226:32: B023 Function definition does not bind loop variable 'dcoll'.
[116](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:117)
test/test_op.py:228:31: B023 Function definition does not bind loop variable 'dcoll'.
[117](https://github.com/inducer/grudge/runs/7155075955?check_suite_focus=true#step:4:118)
test/test_op.py:228:42: B023 Function definition does not bind loop variable 'dd_allfaces'.
```
😱

**Comment by inducer** [comment]
https://github.com/inducer/grudge/pull/273

**Pull request merged**
