### PR TITLE
flake8 on experiments/refinement-playground.py

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by alexfikl** [comment]
Worth moving this to `examples`? So that it stayed `flake8`-ed? (assuming it still runs)

**Comment by inducer** [comment]
Not sure I'd like that in examples. But maybe include experiments in the flake8 check (on Github, Gitlab)? (Could just run black to get things started...)

**Comment by matthiasdiener** [comment]
> Worth moving this to `examples`? So that it stayed `flake8`-ed? (assuming it still runs)

That sounds good to me. What do you think @inducer? Alternatively, we could also add expreiments to CI.

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
