### PR TITLE
Add pytest fixture for PyOpenCLArrayContext

### LINKED ISSUE #28: Provide a pytest fixture for array context creation
To avoid ubiquitous code duplication and gratuitous pyopencl imports.

### PR DESCRIPTION
**Pull request by alexfikl**
Fixes #28.

### CODE REVIEW

**Comment by alexfikl** [comment]
This is more of an RFC at the moment because it just brutishly copies the function from `pyopencl`.

I can refactor `pytest_generate_tests_for_pyopencl` into a separate function that would return the `(arg_names, arg_values, ids)` and then wrap that here to append the array context. Thoughts?

**Comment by inducer** [comment]
> I can refactor `pytest_generate_tests_for_pyopencl` into a separate function that would return the `(arg_names, arg_values, ids)` and then wrap that here to append the array context. Thoughts?

I'd much prefer that to brutish copying. :sauropod: :fire: :axe: :)

**Comment by inducer** [comment]
I've just released PyOpenCL 2020.2.1 to get the CIs to pass.

https://github.com/conda-forge/pyopencl-feedstock/pull/49

**Comment by alexfikl** [comment]
> I've just released PyOpenCL 2020.2.1 to get the CIs to pass.

Thank you! I forgot about that. How can I re-run the CI?

**Comment by inducer** [comment]
There:

grafik

But you might not have that button. I just did.

**Comment by alexfikl** [comment]
> But you might not have that button. I just did.

I don't, no :( Thanks!

**Comment by inducer** [comment]
LGTM. Thanks for working on this!

**Pull request merged**
