### PR TITLE
Skip nodal-dg test when oct2py is not installed

### PR DESCRIPTION
**Pull request by alexfikl**

### CODE REVIEW

**Comment by inducer** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/meshmode/meshmode/test/nodal-dg-master/Codes1.1/CFD2D/CouetteIC2D.m'
```
The issue might be that tests get executed in parallel.

**Comment by alexfikl** [comment]
> The issue might be that tests get executed in parallel.

Yeah, that sounds about right. Thanks for the hint! I added back the `git clone` in the CI, so it should work now.

**Comment by inducer** [comment]
Nah, I'm not a huge fan of having redundant mechanisms to create these checkouts. Simply make it atomic by unzipping in a temporary folder and then moving it into place, taking care to tolerate the folder already being there.

**Comment by alexfikl** [comment]
> Nah, I'm not a huge fan of having redundant mechanisms to create these checkouts. Simply make it atomic by unzipping in a temporary folder and then moving it into place, taking care to tolerate the folder already being there.

Fair enough. I'll get on it!

**Comment by alexfikl** [comment]
@inducer Tests managed to pass and it at least looks less racy now. What do you think?

**Comment by inducer** [comment]
I agree with "less racy". :) LGTM, thanks!

**Pull request merged**
