### PR TITLE
Remove unused iname in kernel

### PR DESCRIPTION
**Pull request by alexfikl**
Found in a [grudge run](https://gitlab.tiker.net/inducer/grudge/-/jobs/161113/raw).

### CODE REVIEW

**Comment by alexfikl** [comment]
The Firedrake CI is failing with the weird
```
module 'pybind11' has no attribute 'get_include'
```
Since that's a different image, I'm guessing there's a version mismatch somewhere, but didn't look into it.

**Comment by inducer** [comment]
> Remove unused iname in kernel

Thanks!

> The Firedrake CI is failing with the weird

Sorry about the flakiness. Here's an attempt: 9c356a7

**Comment by alexfikl** [comment]
> Sorry about the flakiness. Here's an attempt: 9c356a7

That seems to have done the trick! Thanks!

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/meshmode/-/merge_requests/96

**Pull request merged**
